from time import sleep
from os import system

print("Spēle Jums uzdos 3 jautājumus.")
print("!!!Atbilde sastāv no viena vārda un šis vards ir jauzraksta precīzi / pareizi!!!")
print("!!!Atbildes raksti ar mazajiem burtiem!!!")
print("Par katru pareizo atbildi +1 punkts")
print("")

punkti = 0

print("1. Kas ir CPU?")
pirmais = input("Tava atbilde: ")

if pirmais == "procesors":
    punkti = punkti + 1
    system("CLS")
    print("                                                         *#####                 ")
    sleep(0.2)
    print("                                                       ###########              ")
    sleep(0.2)
    print("                                                     ###############            ")
    sleep(0.2)
    print("                                                  *####################         ")
    sleep(0.2)
    print("                                                ########################        ")
    sleep(0.2)
    print("                                              #######################           ")
    sleep(0.2)
    print("                                           .######################              ")
    sleep(0.2)
    print("                    #####                ######################,                ")
    sleep(0.2)
    print("                 ##########            #####################/                   ")
    sleep(0.2)
    print("              ###############.       ####################%                      ")
    sleep(0.2)
    print("           ####################(  #####################                         ")
    sleep(0.2)
    print("           #########################################                            ")
    sleep(0.2)
    print("              ###################################                               ")
    sleep(0.2)
    print("                 ,############################                                  ")
    sleep(0.2)
    print("                     ######################                                     ")
    sleep(0.2)
    print("                        ################                                        ")
    sleep(0.2)
    print("                           ,#########                                           ")
    sleep(0.2)
    print("                               ###                                              ")
    sleep(0.2)
    print("")
    sleep(0.2)
else:
    print("                             (####            /####,                            ")
    sleep(0.2)
    print("                              ######         ######                             ")
    sleep(0.2)
    print("                                ######     ######                               ")
    sleep(0.2)
    print("                                  ###### ######                                 ")
    sleep(0.2)
    print("                                    #########                                   ")
    sleep(0.2)
    print("                                     (#####,                                    ")
    sleep(0.2)
    print("                                    #########                                   ")
    sleep(0.2)
    print("                                  ###### ######                                 ")
    sleep(0.2)
    print("                                ######     ######                               ")
    sleep(0.2)
    print("                              ######         ######                             ")
    sleep(0.2)
    print("                             /####             ####                             ")
    sleep(0.2)
    print("")
    print("Uz jautājumu atbildēji nepareizi!!!")

print("2. Kā sauc vienību, kas mēra datora ātrumu?")
otrais = input("Tava atbilde: ")
    
if otrais == "hertzi":
    punkti = punkti + 1
    system("CLS")
    print("                                                         *#####                 ")
    sleep(0.2)
    print("                                                       ###########              ")
    sleep(0.2)
    print("                                                     ###############            ")
    sleep(0.2)
    print("                                                  *####################         ")
    sleep(0.2)
    print("                                                ########################        ")
    sleep(0.2)
    print("                                              #######################           ")
    sleep(0.2)
    print("                                           .######################              ")
    sleep(0.2)
    print("                    #####                ######################,                ")
    sleep(0.2)
    print("                 ##########            #####################/                   ")
    sleep(0.2)
    print("              ###############.       ####################%                      ")
    sleep(0.2)
    print("           ####################(  #####################                         ")
    sleep(0.2)
    print("           #########################################                            ")
    sleep(0.2)
    print("              ###################################                               ")
    sleep(0.2)
    print("                 ,############################                                  ")
    sleep(0.2)
    print("                     ######################                                     ")
    sleep(0.2)
    print("                        ################                                        ")
    sleep(0.2)
    print("                           ,#########                                           ")
    sleep(0.2)
    print("                               ###                                              ")
    sleep(0.2)
    print("")
    sleep(0.2)
else:
    print("                             (####            /####,                            ")
    sleep(0.2)
    print("                              ######         ######                             ")
    sleep(0.2)
    print("                                ######     ######                               ")
    sleep(0.2)
    print("                                  ###### ######                                 ")
    sleep(0.2)
    print("                                    #########                                   ")
    sleep(0.2)
    print("                                     (#####,                                    ")
    sleep(0.2)
    print("                                    #########                                   ")
    sleep(0.2)
    print("                                  ###### ######                                 ")
    sleep(0.2)
    print("                                ######     ######                               ")
    sleep(0.2)
    print("                              ######         ######                             ")
    sleep(0.2)
    print("                             /####             ####                             ")
    sleep(0.2)
    print("")
    print("Uz jautājumu atbildēji nepareizi!!!")
    
print("3. Kā sauc populārāko programmēšanas valodu, kura sākas uz burta 'p'?")
tresais = input("Tava atbilde: ")

if tresais == "python":
    punkti = punkti + 1
    system("CLS")
    print("                                                         *#####                 ")
    sleep(0.2)
    print("                                                       ###########              ")
    sleep(0.2)
    print("                                                     ###############            ")
    sleep(0.2)
    print("                                                  *####################         ")
    sleep(0.2)
    print("                                                ########################        ")
    sleep(0.2)
    print("                                              #######################           ")
    sleep(0.2)
    print("                                           .######################              ")
    sleep(0.2)
    print("                    #####                ######################,                ")
    sleep(0.2)
    print("                 ##########            #####################/                   ")
    sleep(0.2)
    print("              ###############.       ####################%                      ")
    sleep(0.2)
    print("           ####################(  #####################                         ")
    sleep(0.2)
    print("           #########################################                            ")
    sleep(0.2)
    print("              ###################################                               ")
    sleep(0.2)
    print("                 ,############################                                  ")
    sleep(0.2)
    print("                     ######################                                     ")
    sleep(0.2)
    print("                        ################                                        ")
    sleep(0.2)
    print("                           ,#########                                           ")
    sleep(0.2)
    print("                               ###                                              ")
    sleep(0.2)
    print("")
    sleep(0.2)
else:
    print("                             (####            /####,                            ")
    sleep(0.2)
    print("                              ######         ######                             ")
    sleep(0.2)
    print("                                ######     ######                               ")
    sleep(0.2)
    print("                                  ###### ######                                 ")
    sleep(0.2)
    print("                                    #########                                   ")
    sleep(0.2)
    print("                                     (#####,                                    ")
    sleep(0.2)
    print("                                    #########                                   ")
    sleep(0.2)
    print("                                  ###### ######                                 ")
    sleep(0.2)
    print("                                ######     ######                               ")
    sleep(0.2)
    print("                              ######         ######                             ")
    sleep(0.2)
    print("                             /####             ####                             ")
    sleep(0.2)
    print("")
    print("Uz jautājumu atbildēji nepareizi!!!")

print("")
print("Tavi iegūtie punkti par šiem 3 jautājumiem:", punkti , "no 3")

    


