from time import sleep
from os import system

vards = input("Lūdzu ievadiet savu vārdu: ")
print()
print("Spēle 'Jautājumi par datoru' Jums uzdos 3 jautājumus.")
print()
print("!!!Atbilde sastāv no viena vārda un šis vards ir jauzraksta precīzi / pareizi un bez saīsinājumiem (pilns vārds)!!!")
print()
print("!!!Atbildes raksti ar mazajiem burtiem!!!")
print()
print("Par katru pareizo atbildi +1 punkts")
print()
sleep(5.0)

punkti = 0

while punkti <= 1:
    punkti = punkti - punkti
    print("1. Kas ir CPU?")
    print()
    pirmais = input("Tava atbilde (raksti vienu vārdu): ")
    print()
    if pirmais == "procesors":
        punkti = punkti + 1
        system("CLS")
        print("                                                         *#####                 ")
        sleep(0.2)
        print("                                                       ###########              ")
        sleep(0.2)
        print("                                                     ###############            ")
        sleep(0.2)
        print("                                                  *####################         ")
        sleep(0.2)
        print("                                                ########################        ")
        sleep(0.2)
        print("                                              #######################           ")
        sleep(0.2)
        print("                                           .######################              ")
        sleep(0.2)
        print("                    #####                ######################,                ")
        sleep(0.2)
        print("                 ##########            #####################/                   ")
        sleep(0.2)
        print("              ###############.       ####################%                      ")
        sleep(0.2)
        print("           ####################(  #####################                         ")
        sleep(0.2)
        print("           #########################################                            ")
        sleep(0.2)
        print("              ###################################                               ")
        sleep(0.2)
        print("                 ,############################                                  ")
        sleep(0.2)
        print("                     ######################                                     ")
        sleep(0.2)
        print("                        ################                                        ")
        sleep(0.2)
        print("                           ,#########                                           ")
        sleep(0.2)
        print("                               ###                                              ")
        sleep(0.2)
        print()
        sleep(0.2)
        print()
        sleep(0.2)
        print("Uz jautājumu atbildēji pareizi!!!")
    else:
        print("                             (####            /####,                            ")
        sleep(0.2)
        print("                              ######         ######                             ")
        sleep(0.2)
        print("                                ######     ######                               ")
        sleep(0.2)
        print("                                  ###### ######                                 ")
        sleep(0.2)
        print("                                    #########                                   ")
        sleep(0.2)
        print("                                     (#####,                                    ")
        sleep(0.2)
        print("                                    #########                                   ")
        sleep(0.2)
        print("                                  ###### ######                                 ")
        sleep(0.2)
        print("                                ######     ######                               ")
        sleep(0.2)
        print("                              ######         ######                             ")
        sleep(0.2)
        print("                             /####             ####                             ")
        sleep(0.2)
        print()
        sleep(0.2)
        print("Uz jautājumu atbildēji nepareizi!!!")

    sleep(0.5)
    print()
    print("2. Kā sauc vienību, kas mēra monitora ātrumu?")
    print()
    otrais = input("Tava atbilde (raksti stanadrtvienību): ")
    print()
        
    if otrais == "hertzi":
        punkti = punkti + 1
        system("CLS")
        print("                                                         *#####                 ")
        sleep(0.2)
        print("                                                       ###########              ")
        sleep(0.2)
        print("                                                     ###############            ")
        sleep(0.2)
        print("                                                  *####################         ")
        sleep(0.2)
        print("                                                ########################        ")
        sleep(0.2)
        print("                                              #######################           ")
        sleep(0.2)
        print("                                           .######################              ")
        sleep(0.2)
        print("                    #####                ######################,                ")
        sleep(0.2)
        print("                 ##########            #####################/                   ")
        sleep(0.2)
        print("              ###############.       ####################%                      ")
        sleep(0.2)
        print("           ####################(  #####################                         ")
        sleep(0.2)
        print("           #########################################                            ")
        sleep(0.2)
        print("              ###################################                               ")
        sleep(0.2)
        print("                 ,############################                                  ")
        sleep(0.2)
        print("                     ######################                                     ")
        sleep(0.2)
        print("                        ################                                        ")
        sleep(0.2)
        print("                           ,#########                                           ")
        sleep(0.2)
        print("                               ###                                              ")
        sleep(0.2)
        print()
        sleep(0.2)
        print()
        sleep(0.2)
        print("Uz jautājumu atbildēji pareizi!!!")
    else:
        print("                             (####            /####,                            ")
        sleep(0.2)
        print("                              ######         ######                             ")
        sleep(0.2)
        print("                                ######     ######                               ")
        sleep(0.2)
        print("                                  ###### ######                                 ")
        sleep(0.2)
        print("                                    #########                                   ")
        sleep(0.2)
        print("                                     (#####,                                    ")
        sleep(0.2)
        print("                                    #########                                   ")
        sleep(0.2)
        print("                                  ###### ######                                 ")
        sleep(0.2)
        print("                                ######     ######                               ")
        sleep(0.2)
        print("                              ######         ######                             ")
        sleep(0.2)
        print("                             /####             ####                             ")
        sleep(0.2)
        print()
        sleep(0.2)
        print("Uz jautājumu atbildēji nepareizi!!!")

    sleep(0.5)
    print()  
    print("3. Kā sauc populārāko programmēšanas valodu, kura sākas ar burta 'p'?")
    print()
    tresais = input("Tava atbilde (angliski): ")
    print()

    if tresais == "python":
        punkti = punkti + 1
        system("CLS")
        print("                                                         *#####                 ")
        sleep(0.2)
        print("                                                       ###########              ")
        sleep(0.2)
        print("                                                     ###############            ")
        sleep(0.2)
        print("                                                  *####################         ")
        sleep(0.2)
        print("                                                ########################        ")
        sleep(0.2)
        print("                                              #######################           ")
        sleep(0.2)
        print("                                           .######################              ")
        sleep(0.2)
        print("                    #####                ######################,                ")
        sleep(0.2)
        print("                 ##########            #####################/                   ")
        sleep(0.2)
        print("              ###############.       ####################%                      ")
        sleep(0.2)
        print("           ####################(  #####################                         ")
        sleep(0.2)
        print("           #########################################                            ")
        sleep(0.2)
        print("              ###################################                               ")
        sleep(0.2)
        print("                 ,############################                                  ")
        sleep(0.2)
        print("                     ######################                                     ")
        sleep(0.2)
        print("                        ################                                        ")
        sleep(0.2)
        print("                           ,#########                                           ")
        sleep(0.2)
        print("                               ###                                              ")
        sleep(0.2)
        print()
        sleep(0.2)
        print()
        sleep(0.2)
        print("Uz jautājumu atbildēji pareizi!!!")
    else:
        print("                             (####            /####,                            ")
        sleep(0.2)
        print("                              ######         ######                             ")
        sleep(0.2)
        print("                                ######     ######                               ")
        sleep(0.2)
        print("                                  ###### ######                                 ")
        sleep(0.2)
        print("                                    #########                                   ")
        sleep(0.2)
        print("                                     (#####,                                    ")
        sleep(0.2)
        print("                                    #########                                   ")
        sleep(0.2)
        print("                                  ###### ######                                 ")
        sleep(0.2)
        print("                                ######     ######                               ")
        sleep(0.2)
        print("                              ######         ######                             ")
        sleep(0.2)
        print("                             /####             ####                             ")
        sleep(0.2)
        print()
        sleep(0.2)
        print("Uz jautājumu atbildēji nepareizi!!!")
        print()

    if punkti > 1:
        sleep(0.5)
        print()
        print("Apsveicu", vards , "tavi iegūtie punkti par šo mēģinājumu:", punkti , "no 3")
        sleep(10.0)
    else:
        sleep(0.5)
        print("Nekas", vards , "vari mēģināt vēlreiz, tavi iegūtie punkti par šo mēģinājumu:", punkti , "no 3")
        sleep(10.0)

    


