from time import sleep
from os import system

print("Spēle Jums uzdos 5 jautājumus.")
print("Ja uz kādu jautājumu atbildi nepareizi tad sāc no jauna.")
print("Atbildes raksti ar mazajiem burtiem.")
print("")
print("1. Kas ir CPU?")
pirmais = input("Tava atbilde: ")
if pirmais == "procesors":
    system("CLS")
    print("                                                         *#####                 ")
    sleep(0.2)
    print("                                                       ###########              ")
    sleep(0.2)
    print("                                                     ###############            ")
    sleep(0.2)
    print("                                                  *####################         ")
    sleep(0.2)
    print("                                                ########################        ")
    sleep(0.2)
    print("                                              #######################           ")
    sleep(0.2)
    print("                                           .######################              ")
    sleep(0.2)
    print("                    #####                ######################,                ")
    sleep(0.2)
    print("                 ##########            #####################/                   ")
    sleep(0.2)
    print("              ###############.       ####################%                      ")
    sleep(0.2)
    print("           ####################(  #####################                         ")
    sleep(0.2)
    print("           #########################################                            ")
    sleep(0.2)
    print("              ###################################                               ")
    sleep(0.2)
    print("                 ,############################                                  ")
    sleep(0.2)
    print("                     ######################                                     ")
    sleep(0.2)
    print("                        ################                                        ")
    sleep(0.2)
    print("                           ,#########                                           ")
    sleep(0.2)
    print("                               ###                                              ")
    sleep(0.2)
    print("")
    sleep(0.2)
    print("2. Kā sauc vienību, kas mēra datora ātrumu?")
    otrais = input("Tava atbilde: ")
    if otrais == "hertzos":
        system("CLS")
        print("                                                         *#####                 ")
        sleep(0.2)
        print("                                                       ###########              ")
        sleep(0.2)
        print("                                                     ###############            ")
        sleep(0.2)
        print("                                                  *####################         ")
        sleep(0.2)
        print("                                                ########################        ")
        sleep(0.2)
        print("                                              #######################           ")
        sleep(0.2)
        print("                                           .######################              ")
        sleep(0.2)
        print("                    #####                ######################,                ")
        sleep(0.2)
        print("                 ##########            #####################/                   ")
        sleep(0.2)
        print("              ###############.       ####################%                      ")
        sleep(0.2)
        print("           ####################(  #####################                         ")
        sleep(0.2)
        print("           #########################################                            ")
        sleep(0.2)
        print("              ###################################                               ")
        sleep(0.2)
        print("                 ,############################                                  ")
        sleep(0.2)
        print("                     ######################                                     ")
        sleep(0.2)
        print("                        ################                                        ")
        sleep(0.2)
        print("                           ,#########                                           ")
        sleep(0.2)
        print("                               ###                                              ")
        sleep(0.2)
        print("")
        sleep(0.2)
        print("3. Kā sauc populārāko programmēšanas valodu, kura sākas uz burta 'p'?")
        tresais = input("Tava atbilde: ")
    else:
        print("                             (####            /####,                            ")
        sleep(0.2)
        print("                              ######         ######                             ")
        sleep(0.2)
        print("                                ######     ######                               ")
        sleep(0.2)
        print("                                  ###### ######                                 ")
        sleep(0.2)
        print("                                    #########                                   ")
        sleep(0.2)
        print("                                     (#####,                                    ")
        sleep(0.2)
        print("                                    #########                                   ")
        sleep(0.2)
        print("                                  ###### ######                                 ")
        sleep(0.2)
        print("                                ######     ######                               ")
        sleep(0.2)
        print("                              ######         ######                             ")
        sleep(0.2)
        print("                             /####             ####                             ")
        sleep(0.2)
        print("Uz jautājumu atbildēji nepareizi, mēģini vēlreiz!!!")
        if tresais == "python":
            system("CLS")
            print("                                                         *#####                 ")
            sleep(0.2)
            print("                                                       ###########              ")
            sleep(0.2)
            print("                                                     ###############            ")
            sleep(0.2)
            print("                                                  *####################         ")
            sleep(0.2)
            print("                                                ########################        ")
            sleep(0.2)
            print("                                              #######################           ")
            sleep(0.2)
            print("                                           .######################              ")
            sleep(0.2)
            print("                    #####                ######################,                ")
            sleep(0.2)
            print("                 ##########            #####################/                   ")
            sleep(0.2)
            print("              ###############.       ####################%                      ")
            sleep(0.2)
            print("           ####################(  #####################                         ")
            sleep(0.2)
            print("           #########################################                            ")
            sleep(0.2)
            print("              ###################################                               ")
            sleep(0.2)
            print("                 ,############################                                  ")
            sleep(0.2)
            print("                     ######################                                     ")
            sleep(0.2)
            print("                        ################                                        ")
            sleep(0.2)
            print("                           ,#########                                           ")
            sleep(0.2)
            print("                               ###                                              ")
            sleep(0.2)
            print("")
            sleep(0.2)
            print("Uz visiem jautājumiem esi atbildējis pareizi, malacis!!!")
        else:
        print("                             (####            /####,                            ")
        sleep(0.2)
        print("                              ######         ######                             ")
        sleep(0.2)
        print("                                ######     ######                               ")
        sleep(0.2)
        print("                                  ###### ######                                 ")
        sleep(0.2)
        print("                                    #########                                   ")
        sleep(0.2)
        print("                                     (#####,                                    ")
        sleep(0.2)
        print("                                    #########                                   ")
        sleep(0.2)
        print("                                  ###### ######                                 ")
        sleep(0.2)
        print("                                ######     ######                               ")
        sleep(0.2)
        print("                              ######         ######                             ")
        sleep(0.2)
        print("                             /####             ####                             ")
        sleep(0.2)
        print("Uz jautājumu atbildēji nepareizi, mēģini vēlreiz!!!")
else:
    print("                             (####            /####,                            ")
    sleep(0.2)
    print("                              ######         ######                             ")
    sleep(0.2)
    print("                                ######     ######                               ")
    sleep(0.2)
    print("                                  ###### ######                                 ")
    sleep(0.2)
    print("                                    #########                                   ")
    sleep(0.2)
    print("                                     (#####,                                    ")
    sleep(0.2)
    print("                                    #########                                   ")
    sleep(0.2)
    print("                                  ###### ######                                 ")
    sleep(0.2)
    print("                                ######     ######                               ")
    sleep(0.2)
    print("                              ######         ######                             ")
    sleep(0.2)
    print("                             /####             ####                             ")
    sleep(0.2)
    print("Uz jautājumu atbildēji nepareizi, mēģini vēlreiz!!!")

    


